version: 2
defaults: &defaults
  docker:
    - image: circleci/node:12.14.1
  working_directory: ~/repo
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-
      - run: yarn
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
              - node_modules/
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build

workflows:
  version: 2
  deploy-vue-event-listener:
    jobs:
      - install
      - build:
          requires:
            - install
          filters:
            branches:
              only: /^master/
